services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dummyuser
      POSTGRES_PASSWORD: dummypass
      POSTGRES_DB: dummydb
    ports:
      - "5432:5432"

  backend:
    build: ./Back
    environment:
      PGHOST: db
      PGUSER: dummyuser
      PGPASSWORD: dummypass
      PGDATABASE: dummydb
      PGPORT: 5432
    ports:
      - "8000:8000"
  frontend:
    build: ./Front
    ports:
      - "3000:3000"
